// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebHook.Infrastructure.Data_Persistence;

#nullable disable

namespace WebHook.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20260731160808_AddDeliveryStatusConstraintToDelivery")]
    partial class AddDeliveryStatusConstraintToDelivery
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebHook.Core.Entities.WebHookEventCatalog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvailableFields")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("NormalizedEventName")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasComputedColumnSql("UPPER(\"EventName\")", true);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEventName")
                        .IsUnique();

                    b.ToTable("WebHookEventCatalogs");
                });

            modelBuilder.Entity("WebHook.Core.Entities.WebhookDeadLetterQueue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<Guid>("WebhookDeliveryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "WebhookDeliveryId" }, "IX_Webhook_DeadLetter_DeliveryId");

                    b.ToTable("WebhookDeadLetterQueues");
                });

            modelBuilder.Entity("WebHook.Core.Entities.WebhookDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CallBackUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeliveryStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("NextRetryAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestPayload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid>("WebhookEventId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WebhookSubscriptionEventId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryStatus");

                    b.HasIndex("WebhookEventId");

                    b.HasIndex("WebhookSubscriptionEventId");

                    b.ToTable("WebhookDeliveries", t =>
                        {
                            t.HasCheckConstraint("CK_WebhookDelivery_DeliveredSttatus", "\"DeliveryStatus\" != 'Delivered' OR \"DeliveredAt\" IS NOT NULL");

                            t.HasCheckConstraint("CK_WebhookDelivery_RetryCount", "\"RetryCount\" >= 0");

                            t.HasCheckConstraint("CK_WebhookDelivery_Status", "\"DeliveryStatus\" IN ('Pending', 'Processing', 'Delivered', 'Failed', 'Retrying', 'DeadLetter')");
                        });
                });

            modelBuilder.Entity("WebHook.Core.Entities.WebhookDeliveryAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AttemptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("AttemptedCount")
                        .HasColumnType("integer");

                    b.Property<long>("Duration")
                        .HasColumnType("bigint");

                    b.Property<string>("HttpResponse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HttpResponseCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WebhookDeliveryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WebhookDeliveryId");

                    b.ToTable("WebhookDeliveryAttempts");
                });

            modelBuilder.Entity("WebHook.Core.Entities.WebhookEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PayLoad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CorrelationId", "EventType" }, "IX_Webhook_Event_CorrelationId_EventType");

                    b.HasIndex(new[] { "CreatedAt" }, "IX_Webhook_Event_CreatedAt");

                    b.HasIndex(new[] { "ProcessedAt" }, "IX_Webhook_Event_ProcessedAt");

                    b.HasIndex(new[] { "Status" }, "IX_Webhook_Event_Status");

                    b.ToTable("WebhookEvents", t =>
                        {
                            t.HasCheckConstraint("CK_WebhookEvents_ProcessedAt_After_CreatedAt", "\"ProcessedAt\" IS NULL OR \"ProcessedAt\" >= \"CreatedAt\"");

                            t.HasCheckConstraint("CK_WebhookEvents_Status", "\"Status\" IN ('Pending', 'Processing', 'Processed', 'PartiallyProcessed' , 'Failed')");
                        });
                });

            modelBuilder.Entity("WebHook.Core.Entities.WebhookSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CallbackUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SecretKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<string>("SubscribedFields")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("WebhookSubscriptions");
                });

            modelBuilder.Entity("WebHook.Core.Entities.WebhookSubscriptionEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid>("WebhookEventCatalogId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WebhookSubscriptionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("WebhookSubscriptionId");

                    b.HasIndex("WebhookEventCatalogId", "WebhookSubscriptionId")
                        .IsUnique()
                        .HasDatabaseName("IX_Webhook_Event_Subscription");

                    b.ToTable("WebhookEventSubscriptions");
                });

            modelBuilder.Entity("WebHook.Core.Entities.WebhookDeadLetterQueue", b =>
                {
                    b.HasOne("WebHook.Core.Entities.WebhookDelivery", "webhookDelivery")
                        .WithMany("webhookDeadLetterQueues")
                        .HasForeignKey("WebhookDeliveryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("webhookDelivery");
                });

            modelBuilder.Entity("WebHook.Core.Entities.WebhookDelivery", b =>
                {
                    b.HasOne("WebHook.Core.Entities.WebhookEvent", "webhookEvent")
                        .WithMany("WebhookDeliveries")
                        .HasForeignKey("WebhookEventId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WebHook.Core.Entities.WebhookSubscriptionEvent", "WebhookSubscriptionEvent")
                        .WithMany("WebhookDeliveries")
                        .HasForeignKey("WebhookSubscriptionEventId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("WebhookSubscriptionEvent");

                    b.Navigation("webhookEvent");
                });

            modelBuilder.Entity("WebHook.Core.Entities.WebhookDeliveryAttempt", b =>
                {
                    b.HasOne("WebHook.Core.Entities.WebhookDelivery", "webhookDelivery")
                        .WithMany("WebhookDeliveryAttempts")
                        .HasForeignKey("WebhookDeliveryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("webhookDelivery");
                });

            modelBuilder.Entity("WebHook.Core.Entities.WebhookSubscriptionEvent", b =>
                {
                    b.HasOne("WebHook.Core.Entities.WebHookEventCatalog", "webHookEventCatalog")
                        .WithMany("WebhookSubscriptions")
                        .HasForeignKey("WebhookEventCatalogId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WebHook.Core.Entities.WebhookSubscription", "webhookSubscription")
                        .WithMany("WebhookEvents")
                        .HasForeignKey("WebhookSubscriptionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("webHookEventCatalog");

                    b.Navigation("webhookSubscription");
                });

            modelBuilder.Entity("WebHook.Core.Entities.WebHookEventCatalog", b =>
                {
                    b.Navigation("WebhookSubscriptions");
                });

            modelBuilder.Entity("WebHook.Core.Entities.WebhookDelivery", b =>
                {
                    b.Navigation("WebhookDeliveryAttempts");

                    b.Navigation("webhookDeadLetterQueues");
                });

            modelBuilder.Entity("WebHook.Core.Entities.WebhookEvent", b =>
                {
                    b.Navigation("WebhookDeliveries");
                });

            modelBuilder.Entity("WebHook.Core.Entities.WebhookSubscription", b =>
                {
                    b.Navigation("WebhookEvents");
                });

            modelBuilder.Entity("WebHook.Core.Entities.WebhookSubscriptionEvent", b =>
                {
                    b.Navigation("WebhookDeliveries");
                });
#pragma warning restore 612, 618
        }
    }
}
