// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebHook.Infrastructure.Data_Persistence;

#nullable disable

namespace WebHook.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("WebHook.Core.Entities.OtpOperationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Jti")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OtpVerificationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OtpVerificationId1")
                        .HasColumnType("uuid");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ConsumedAt");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Jti")
                        .IsUnique();

                    b.HasIndex("OtpVerificationId");

                    b.HasIndex("OtpVerificationId1");

                    b.HasIndex("UserId");

                    b.ToTable("OtpOperationTokens");
                });

            modelBuilder.Entity("WebHook.Core.Entities.OtpVerification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FailedAttemptCount")
                        .HasColumnType("integer");

                    b.Property<bool>("IsConsumed")
                        .HasColumnType("boolean");

                    b.Property<string>("OtpHash")
                        .HasColumnType("text");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ValidatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConsumedAt");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Purpose");

                    b.HasIndex("UserId");

                    b.HasIndex("ValidatedAt");

                    b.ToTable("OtpVerifications");
                });

            modelBuilder.Entity("WebHook.Core.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            ConcurrencyStamp = "ec511bd4-4853-426a-a2fc-751886560c9a",
                            Description = "Administrator role with full access",
                            IsActive = true,
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-f6a7-8901-bcde-f12345678901"),
                            ConcurrencyStamp = "d1f2e3c4-b5a6-7890-cdef-123456789012",
                            Description = "Regular user role with limited access",
                            IsActive = true,
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-a7b8-9012-cdef-123456789012"),
                            ConcurrencyStamp = "f1e2d3c4-b5a6-7890-cdef-123456789012",
                            Description = "System role with administrative privileges",
                            IsActive = true,
                            Name = "System",
                            NormalizedName = "SYSTEM"
                        });
                });

            modelBuilder.Entity("WebHook.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeactivationJustification")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTimeOffset?>("LastAuthenticatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastLoginDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("TokenExpirationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex(new[] { "CreatedAt" }, "IX_User_CreatedAt");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("WebHook.Core.Entities.WebHookEventCatalog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvailableFields")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("NormalizedEventName")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasComputedColumnSql("UPPER(\"EventName\")", true);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEventName")
                        .IsUnique();

                    b.ToTable("WebHookEventCatalogs");
                });

            modelBuilder.Entity("WebHook.Core.Entities.WebhookDeadLetterQueue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("RetriedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RetriedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RetryJustification")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("WebhookDeliveryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "WebhookDeliveryId" }, "IX_Webhook_DeadLetter_DeliveryId");

                    b.ToTable("WebhookDeadLetterQueues");
                });

            modelBuilder.Entity("WebHook.Core.Entities.WebhookDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CallBackUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeliveryStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("NextRetryAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestPayload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("RetryCycle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<Guid>("WebhookEventId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WebhookSubscriptionEventId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryStatus");

                    b.HasIndex("WebhookEventId");

                    b.HasIndex("WebhookSubscriptionEventId");

                    b.ToTable("WebhookDeliveries", t =>
                        {
                            t.HasCheckConstraint("CK_WebhookDelivery_DeliveredSttatus", "\"DeliveryStatus\" != 'Delivered' OR \"DeliveredAt\" IS NOT NULL");

                            t.HasCheckConstraint("CK_WebhookDelivery_RetryCount", "\"RetryCount\" >= 0");

                            t.HasCheckConstraint("CK_WebhookDelivery_Status", "\"DeliveryStatus\" IN ('Pending', 'Processing', 'Delivered', 'Failed', 'Retrying', 'DeadLetter')");
                        });
                });

            modelBuilder.Entity("WebHook.Core.Entities.WebhookDeliveryAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AttemptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("AttemptedCount")
                        .HasColumnType("integer");

                    b.Property<double>("Duration")
                        .HasColumnType("double precision");

                    b.Property<string>("HttpResponse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HttpResponseCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WebhookDeliveryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WebhookDeliveryId");

                    b.ToTable("WebhookDeliveryAttempts", t =>
                        {
                            t.HasCheckConstraint("CK_DeliveryAttempt_AttemptedCountGreaterThanZero", "\"AttemptedCount\" > 0");

                            t.HasCheckConstraint("CK_DeliveryAttempt_DurationGreaterThanZero", "\"Duration\" > 0");
                        });
                });

            modelBuilder.Entity("WebHook.Core.Entities.WebhookEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PayLoad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("EventType");

                    b.HasIndex(new[] { "CorrelationId", "EventType" }, "IX_Webhook_Event_CorrelationId_EventType")
                        .IsUnique();

                    b.HasIndex(new[] { "CreatedAt" }, "IX_Webhook_Event_CreatedAt");

                    b.HasIndex(new[] { "ProcessedAt" }, "IX_Webhook_Event_ProcessedAt");

                    b.HasIndex(new[] { "Status" }, "IX_Webhook_Event_Status");

                    b.ToTable("WebhookEvents", t =>
                        {
                            t.HasCheckConstraint("CK_WebhookEvents_ProcessedAt_After_CreatedAt", "\"ProcessedAt\" IS NULL OR \"ProcessedAt\" >= \"CreatedAt\"");

                            t.HasCheckConstraint("CK_WebhookEvents_Status", "\"Status\" IN ('Pending', 'Processing', 'Processed', 'PartiallyProcessed' , 'Failed')");
                        });
                });

            modelBuilder.Entity("WebHook.Core.Entities.WebhookServiceClient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ClientKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeactivatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("ServiceClientName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ServiceClientName");

                    b.ToTable("WebhookServiceClients");
                });

            modelBuilder.Entity("WebHook.Core.Entities.WebhookServiceClientEventCatalog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeactivatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("EventCatalogId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ServiceClientId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DeactivatedAt");

                    b.HasIndex("EventCatalogId", "ServiceClientId")
                        .IsUnique();

                    b.HasIndex(new[] { "CreatedAt" }, "IX_CreatedAt");

                    b.HasIndex(new[] { "EventCatalogId" }, "IX_ServiceClient_CatalogId");

                    b.HasIndex(new[] { "ServiceClientId" }, "IX_ServiceClient_ServiceCleintId");

                    b.ToTable("WebhookServiceClientEventCatalogs");
                });

            modelBuilder.Entity("WebHook.Core.Entities.WebhookSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CallbackUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SecretKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<string>("SubscribedFields")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("WebhookSubscriptions");
                });

            modelBuilder.Entity("WebHook.Core.Entities.WebhookSubscriptionEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid>("WebhookEventCatalogId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WebhookSubscriptionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("WebhookSubscriptionId");

                    b.HasIndex("WebhookEventCatalogId", "WebhookSubscriptionId")
                        .IsUnique()
                        .HasDatabaseName("IX_Webhook_Event_Subscription");

                    b.ToTable("WebhookEventSubscriptions");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("WebHook.Core.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("WebHook.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("WebHook.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("WebHook.Core.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebHook.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("WebHook.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebHook.Core.Entities.OtpOperationToken", b =>
                {
                    b.HasOne("WebHook.Core.Entities.OtpVerification", "OtpVerification")
                        .WithMany()
                        .HasForeignKey("OtpVerificationId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("WebHook.Core.Entities.OtpVerification", null)
                        .WithMany("OperationTokens")
                        .HasForeignKey("OtpVerificationId1");

                    b.HasOne("WebHook.Core.Entities.User", "UserToPerformOperation")
                        .WithMany("OtpOperationTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.ClientNoAction);

                    b.Navigation("OtpVerification");

                    b.Navigation("UserToPerformOperation");
                });

            modelBuilder.Entity("WebHook.Core.Entities.OtpVerification", b =>
                {
                    b.HasOne("WebHook.Core.Entities.User", "UserToVerify")
                        .WithMany("OtpVerifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("UserToVerify");
                });

            modelBuilder.Entity("WebHook.Core.Entities.WebhookDeadLetterQueue", b =>
                {
                    b.HasOne("WebHook.Core.Entities.WebhookDelivery", "webhookDelivery")
                        .WithMany("webhookDeadLetterQueues")
                        .HasForeignKey("WebhookDeliveryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("webhookDelivery");
                });

            modelBuilder.Entity("WebHook.Core.Entities.WebhookDelivery", b =>
                {
                    b.HasOne("WebHook.Core.Entities.WebhookEvent", "webhookEvent")
                        .WithMany("WebhookDeliveries")
                        .HasForeignKey("WebhookEventId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WebHook.Core.Entities.WebhookSubscriptionEvent", "WebhookSubscriptionEvent")
                        .WithMany("WebhookDeliveries")
                        .HasForeignKey("WebhookSubscriptionEventId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("WebhookSubscriptionEvent");

                    b.Navigation("webhookEvent");
                });

            modelBuilder.Entity("WebHook.Core.Entities.WebhookDeliveryAttempt", b =>
                {
                    b.HasOne("WebHook.Core.Entities.WebhookDelivery", "webhookDelivery")
                        .WithMany("WebhookDeliveryAttempts")
                        .HasForeignKey("WebhookDeliveryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("webhookDelivery");
                });

            modelBuilder.Entity("WebHook.Core.Entities.WebhookServiceClientEventCatalog", b =>
                {
                    b.HasOne("WebHook.Core.Entities.WebHookEventCatalog", "eventCatalog")
                        .WithMany("WebhookServiceClients")
                        .HasForeignKey("EventCatalogId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("WebHook.Core.Entities.WebhookServiceClient", "serviceClient")
                        .WithMany("EventCatalogs")
                        .HasForeignKey("ServiceClientId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("eventCatalog");

                    b.Navigation("serviceClient");
                });

            modelBuilder.Entity("WebHook.Core.Entities.WebhookSubscription", b =>
                {
                    b.HasOne("WebHook.Core.Entities.User", "CreatedByUser")
                        .WithMany("WebhookSubscriptions")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("WebHook.Core.Entities.WebhookSubscriptionEvent", b =>
                {
                    b.HasOne("WebHook.Core.Entities.WebHookEventCatalog", "webHookEventCatalog")
                        .WithMany("WebhookSubscriptions")
                        .HasForeignKey("WebhookEventCatalogId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WebHook.Core.Entities.WebhookSubscription", "webhookSubscription")
                        .WithMany("WebhookEvents")
                        .HasForeignKey("WebhookSubscriptionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("webHookEventCatalog");

                    b.Navigation("webhookSubscription");
                });

            modelBuilder.Entity("WebHook.Core.Entities.OtpVerification", b =>
                {
                    b.Navigation("OperationTokens");
                });

            modelBuilder.Entity("WebHook.Core.Entities.User", b =>
                {
                    b.Navigation("OtpOperationTokens");

                    b.Navigation("OtpVerifications");

                    b.Navigation("WebhookSubscriptions");
                });

            modelBuilder.Entity("WebHook.Core.Entities.WebHookEventCatalog", b =>
                {
                    b.Navigation("WebhookServiceClients");

                    b.Navigation("WebhookSubscriptions");
                });

            modelBuilder.Entity("WebHook.Core.Entities.WebhookDelivery", b =>
                {
                    b.Navigation("WebhookDeliveryAttempts");

                    b.Navigation("webhookDeadLetterQueues");
                });

            modelBuilder.Entity("WebHook.Core.Entities.WebhookEvent", b =>
                {
                    b.Navigation("WebhookDeliveries");
                });

            modelBuilder.Entity("WebHook.Core.Entities.WebhookServiceClient", b =>
                {
                    b.Navigation("EventCatalogs");
                });

            modelBuilder.Entity("WebHook.Core.Entities.WebhookSubscription", b =>
                {
                    b.Navigation("WebhookEvents");
                });

            modelBuilder.Entity("WebHook.Core.Entities.WebhookSubscriptionEvent", b =>
                {
                    b.Navigation("WebhookDeliveries");
                });
#pragma warning restore 612, 618
        }
    }
}
