// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebHook.Infrastructure.Data_Persistence;

#nullable disable

namespace WebHook.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebHook.Core.Entities.WebHookEventCatalog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string>("AvailableFields")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("NormalizedEventName")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasComputedColumnSql("UPPER(\"EventName\")", true);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEventName")
                        .IsUnique();

                    b.ToTable("WebHookEventCatalogs", (string)null);
                });

            modelBuilder.Entity("WebHook.Core.Entities.WebhookDeadLetterQueue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<Guid>("WebhookDeliveryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "WebhookDeliveryId" }, "IX_Webhook_DeadLetter_DeliveryId");

                    b.ToTable("WebhookDeadLetterQueues", (string)null);
                });

            modelBuilder.Entity("WebHook.Core.Entities.WebhookDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeliveryStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("NextRetryAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestPayload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid>("WebhookEventCatalogId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WebhookEventId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WebhookSubscriptionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WebhookEventCatalogId");

                    b.HasIndex("WebhookEventId");

                    b.HasIndex("WebhookSubscriptionId");

                    b.ToTable("WebhookDeliveries", (string)null);
                });

            modelBuilder.Entity("WebHook.Core.Entities.WebhookDeliveryAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AttemptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("AttemptedCount")
                        .HasColumnType("integer");

                    b.Property<long>("Duration")
                        .HasColumnType("bigint");

                    b.Property<string>("HttpResponse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HttpResponseCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WebhookDeliveryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WebhookDeliveryId");

                    b.ToTable("WebhookDeliveryAttempts", (string)null);
                });

            modelBuilder.Entity("WebHook.Core.Entities.WebhookEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PayLoad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CorrelationId" }, "IX_Webhook_Event_CorrelationId");

                    b.HasIndex(new[] { "EventType" }, "IX_Webhook_Event_EventType");

                    b.ToTable("WebhookEvents", (string)null);
                });

            modelBuilder.Entity("WebHook.Core.Entities.WebhookSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CallbackUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SecretKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<string>("SubscribedFields")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("WebhookSubscriptions", (string)null);
                });

            modelBuilder.Entity("WebHook.Core.Entities.WebhookSubscriptionEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("WebhookEventCatalogId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WebhookSubscriptionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WebhookSubscriptionId");

                    b.HasIndex("WebhookEventCatalogId", "WebhookSubscriptionId")
                        .IsUnique()
                        .HasDatabaseName("IX_Webhook_Event_Subscription");

                    b.ToTable("WebhookEventSubscriptions", (string)null);
                });

            modelBuilder.Entity("WebHook.Core.Entities.WebhookDeadLetterQueue", b =>
                {
                    b.HasOne("WebHook.Core.Entities.WebhookDelivery", "webhookDelivery")
                        .WithMany("webhookDeadLetterQueues")
                        .HasForeignKey("WebhookDeliveryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("webhookDelivery");
                });

            modelBuilder.Entity("WebHook.Core.Entities.WebhookDelivery", b =>
                {
                    b.HasOne("WebHook.Core.Entities.WebHookEventCatalog", "webHookEventCatalog")
                        .WithMany("WebhookDeliveries")
                        .HasForeignKey("WebhookEventCatalogId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WebHook.Core.Entities.WebhookEvent", "webhookEvent")
                        .WithMany("WebhookDeliveries")
                        .HasForeignKey("WebhookEventId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WebHook.Core.Entities.WebhookSubscription", "webhookSubscription")
                        .WithMany("WebhookDeliveries")
                        .HasForeignKey("WebhookSubscriptionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("webHookEventCatalog");

                    b.Navigation("webhookEvent");

                    b.Navigation("webhookSubscription");
                });

            modelBuilder.Entity("WebHook.Core.Entities.WebhookDeliveryAttempt", b =>
                {
                    b.HasOne("WebHook.Core.Entities.WebhookDelivery", "webhookDelivery")
                        .WithMany("WebhookDeliveryAttempts")
                        .HasForeignKey("WebhookDeliveryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("webhookDelivery");
                });

            modelBuilder.Entity("WebHook.Core.Entities.WebhookSubscriptionEvent", b =>
                {
                    b.HasOne("WebHook.Core.Entities.WebHookEventCatalog", "webHookEventCatalog")
                        .WithMany("WebhookSubscriptions")
                        .HasForeignKey("WebhookSubscriptionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WebHook.Core.Entities.WebhookSubscription", "webhookSubscription")
                        .WithMany("WebhookEvents")
                        .HasForeignKey("WebhookSubscriptionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("webHookEventCatalog");

                    b.Navigation("webhookSubscription");
                });

            modelBuilder.Entity("WebHook.Core.Entities.WebHookEventCatalog", b =>
                {
                    b.Navigation("WebhookDeliveries");

                    b.Navigation("WebhookSubscriptions");
                });

            modelBuilder.Entity("WebHook.Core.Entities.WebhookDelivery", b =>
                {
                    b.Navigation("WebhookDeliveryAttempts");

                    b.Navigation("webhookDeadLetterQueues");
                });

            modelBuilder.Entity("WebHook.Core.Entities.WebhookEvent", b =>
                {
                    b.Navigation("WebhookDeliveries");
                });

            modelBuilder.Entity("WebHook.Core.Entities.WebhookSubscription", b =>
                {
                    b.Navigation("WebhookDeliveries");

                    b.Navigation("WebhookEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
